CREATE TABLE STUDENT
(
    ID   VARCHAR2(10) PRIMARY KEY,
    NAME VARCHAR2(30),
    KOR  NUMBER(3),
    ENG  NUMBER(3),
    MATH NUMBER(3)
);

INSERT INTO STUDENT (ID, NAME, KOR, ENG, MATH)
VALUES ('2020001', '홍길동', 100, 90, 80);
COMMIT;

UPDATE STUDENT
SET KOR  = 99,
    ENG  = 88,
    MATH = 77
WHERE ID = '2020001';
COMMIT;

SELECT ID, NAME, KOR, ENG, MATH
FROM STUDENT
WHERE ID = '2020001';

DELETE
FROM STUDENT
WHERE ID = '2020001';
COMMIT;
ROLLBACK; -- 마지막 커밋으로 롤백

create Table TB_Goods
(
    id    NUMBER(4) primary key,
    name  varchar2(30),
    price number(10)
);

DROP TABLE TMP;
CREATE TABLE TMP
(
    ID_TMP NUMBER(10),
    NAME VARCHAR2(30)
);

SELECT * FROM TMP;

CREATE SEQUENCE ID_TMP_INCRE START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE ID_TMP_INCRE;

INSERT INTO TMP VALUES(ID_TMP_INCRE.nextval, 'WORLD3');
select id_tmp_incre.currval from dual;


CREATE SEQUENCE GOODS_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;