SELECT *
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE ID = '2020002'
  AND NAME = '홍길동'; -- Statement

SELECT *
FROM STUDENT
WHERE ID = :id
  AND NAME = :name; -- Statement

ALTER TABLE STUDENT
    MODIFY KOR DEFAULT 0
    MODIFY ENG DEFAULT 0
    MODIFY MATH DEFAULT 0;

ALTER TABLE STUDENT
    ADD TOT NUMBER(3)    DEFAULT 0
    ADD AVG NUMBER(4, 1) DEFAULT 0;

UPDATE STUDENT
SET TOT = KOR + ENG + MATH;

UPDATE STUDENT
SET AVG = TOT / 3;

UPDATE STUDENT
SET TOT = KOR + ENG + MATH
  , AVG = (KOR + ENG + MATH) / 3;

SELECT *
FROM STUDENT;

COMMIT;