/*
    sum, avg, count, max, min
*/

SELECT COUNT(SALARY), SUM(SALARY), AVG(SALARY), SUM(SALARY)/COUNT(SALARY)
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG'

-- 에러나는 문장
SELECT EMPLOYEE_ID, COUNT(SALARY), SUM(SALARY)
FROM EMPLOYEES;

/*
    GROUP BY, HAVING
*/

SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID ASC;

SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

SELECT JOB_ID, SUM(SALARY), AVG(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING SUM(SALARY) >= 10000;

SELECT FIRST_NAME, NVL(COMMISSION_PCT, 0)
FROM EMPLOYEES;

SELECT FIRST_NAME, NVL2(COMMISSION_PCT, 1, 0)
FROM EMPLOYEES;

-- 급여가 5천이상 받는 사원만으로 합계를 내서 업무로 그룹화하여 급여 합계가 2만을 초과하는 업무명을 구하라.
SELECT JOB_ID
FROM EMPLOYEES
WHERE SALARY >= 5000
GROUP BY JOB_ID
HAVING SUM(SALARY) > 20000;

