/*
    순위 함수
    RANK()          1 2 3 3 5 6
    DENSE_RANK()    1 2 3 3 4 5
    ROW_NUMBER()    1 2 3 4 5 6
    ROWNUMBER       1 2 3 4 5 6

    BBS - 게시판
*/

SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID >= 100
  AND EMPLOYEE_ID <= 109;


-- OVER()
-- SELECT 절에서만 사용
-- GROUP BY 보강하기 위해 나온 함수

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES; -- 이걸 하려면 GROUP BY 로 묶어야 하낟

SELECT DEPARTMENT_ID, COUNT(*) OVER ()
FROM EMPLOYEES;

SELECT DEPARTMENT_NAME, COUNT(*) OVER (PARTITION BY DEPARTMENT_ID)
FROM DEPARTMENTS;

SELECT FIRST_NAME,
       RANK() OVER (ORDER BY SALARY DESC)       AS RANK,
       DENSE_RANK() over (ORDER BY SALARY DESC) AS DENSE_RANK,
       ROW_NUMBER() over (ORDER BY SALARY DESC) AS ROW_NUMBER
FROM EMPLOYEES;

SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE ROWNUM <= 10;

SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE ROWNUM between 10 and 20;
-- 이 쿼리는 생각대로 동작되지 않는다.

-- 1. 순위 설정
-- 2. 번호 할당
-- 3. 범위 설정

SELECT *
FROM (SELECT ROWNUM AS RNUM, EMPLOYEE_ID, FIRST_NAME, SALARY
      FROM (SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
            FROM EMPLOYEES
            ORDER BY SALARY DESC))
WHERE RNUM BETWEEN 10 AND 20;