/*
    Table
        : 가로(row), 세로(column)
        create
        drop
        alter

        data
            insert
            delete
            select
            update
*/

CREATE TABLE TB_TEST01
(
    COL1 VARCHAR2(10),
    COL2 VARCHAR2(10),
    COL3 VARCHAR2(10)
);

DROP TABLE TB_TEST01;

CREATE TABLE TB_TEST02
(
    COL1 VARCHAR2(10),
    COL2 NUMBER(5, 1),
    COL3 DATE
);

-- TABLE COPY : 데이터 포함
CREATE TABLE TB_TEST03
AS (SELECT *
    FROM EMPLOYEES);

SELECT *
FROM TB_TEST03;

DROP TABLE TB_TEST03;

CREATE TABLE TB_TEST03(EMPNO, ENAME, SAL)
AS (SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
    FROM EMPLOYEES);

CREATE TABLE TB_DEPTGROUP(DNUM, DCOUNT)
AS (SELECT DEPARTMENT_ID, COUNT(*)
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID);

SELECT *
FROM TB_DEPTGROUP;

-- TABLE COPY : 데이터 미포함
CREATE TABLE TB_TEST04
AS (SELECT *
    FROM DEPARTMENTS
    WHERE 0 = 1);

SELECT *
FROM TB_TEST04;

-- 조인된 테이블 복사
CREATE TABLE DEPT_EMP(EMPNO, SAL, DNAME, LOC)
AS (SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_NAME, LOCATION_ID
    FROM EMPLOYEES E
             INNER JOIN DEPARTMENTS D on D.DEPARTMENT_ID = E.DEPARTMENT_ID);

SELECT *
FROM DEPT_EMP;

-- 테이블명 수정
ALTER TABLE TB_TEST04
    RENAME TO TB_TEST99;

-- 컬럼 추가
ALTER TABLE TB_TEST99
    ADD NEWCOL VARCHAR2(20);

-- 다중 컬럼 추가
ALTER TABLE TB_TEST99
    ADD (COLNEW1 NUMBER,
         COLNEW2 DATE);

-- 단일 컬럼 수정
ALTER TABLE TB_TEST99
    MODIFY NEWCOL VARCHAR2(30);

-- 다중 컬럼 수정
ALTER TABLE TB_TEST99
    MODIFY (COLNEW1 VARCHAR2(20),
            COLNEW2 VARCHAR2(30));

-- 컬럼 삭제
ALTER TABLE TB_TEST99
    DROP COLUMN NEWCOL;

-- 다중 컬럼 삭제
ALTER TABLE TB_TEST99
    DROP (COLNEW1, COLNEW2);

-- 컬럼명 수정
ALTER TABLE TB_TEST99
    RENAME COLUMN DEPARTMENT_ID TO DEPTNO;

DROP TABLE TB_TEST99;

-- 휴지통 비우기
PURGE RECYCLEBIN;


/* INSERT */
INSERT INTO TB_TEST04(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES (100, '기획부', 20, 200);

SELECT *
FROM TB_TEST04;

INSERT INTO TB_TEST04(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (100, '기획부');

INSERT INTO TB_TEST04
VALUES (101, '관리부', 30, 400);

INSERT INTO TB_TEST04(MANAGER_ID, LOCATION_ID, DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (50, 500, 102, '영업부');


/* DELETE */
DELETE
FROM TB_TEST04
WHERE MANAGER_ID = 20;

DELETE
FROM TB_TEST04
WHERE MANAGER_ID IS NULL;

DELETE
FROM TB_TEST04
WHERE MANAGER_ID = 10
  AND ROWNUM = 1;

/* UPDATE */
UPDATE TB_TEST04
SET MANAGER_ID = 40
WHERE DEPARTMENT_NAME = '영업부';

UPDATE TB_TEST04
SET MANAGER_ID    = 10,
    LOCATION_ID   = 100,
    DEPARTMENT_ID = 1000
-- WHERE DEPARTMENT_NAME = '관리부';
WHERE DEPARTMENT_ID > 100;