-- ORDER BY = SORTING
/*
    DB -> Sorting -> Java : 성능이 훨씬 좋다.
    DB -> Java -> Sorting

    SELECT *
    FROM TABLE
    ORDER BY sal ASC -- 오름차순
    ORDER BY sal DESC -- 내림차순
*/

SELECT ENAME, SAL
FROM EMP
ORDER BY SAL ASC;

SELECT ENAME, SAL
FROM EMP
ORDER BY SAL DESC;

-- ALIAS
SELECT EMPNO, ENAME, SAL * 12 AS ANNSAL
FROM EMP
ORDER BY ANNSAL DESC;

SELECT ENAME, COMM
FROM EMP
ORDER BY COMM NULLS FIRST; -- null이 있으면 먼저 출력하라.

SELECT ENAME, COMM
FROM EMP
ORDER BY COMM NULLS LAST; -- null이 있으면 먼저 출력하라.

SELECT ENAME, JOB, SAL
FROM EMP
ORDER BY JOB ASC, SAL DESC;

-- 두 날짜간의 월수(월간격)
SELECT MONTHS_BETWEEN('2021-04-13', SYSDATE)
FROM DUAL;

SELECT MONTHS_BETWEEN('2021-04-13', '2020-11-10')
FROM DUAL;

-- 특정 날짜 월에 정수를 더한 다음 해당 날짜를 반환
SELECT ADD_MONTHS('2020-12-01', 6)
FROM DUAL;

-- 날짜 정보, 연도, 월, 일, 시, 분, 초
SELECT EXTRACT(YEAR FROM TO_DATE('20-12-07', 'YY-MM-DD')) AS 연도,
       EXTRACT(MONTH FROM SYSDATE) AS 월,
       EXTRACT(DAY FROM SYSDATE) AS 일,
       EXTRACT(HOUR FROM CAST(SYSDATE AS TIMESTAMP)) AS 시,
       EXTRACT(MINUTE FROM CAST(SYSDATE AS TIMESTAMP)) AS 분,
       EXTRACT(SECOND FROM CAST(SYSDATE AS TIMESTAMP)) AS 초
FROM DUAL;