SELECT * FROM EMP;

-- 현재 스키마의 모든 테이블 출력
SELECT * FROM TAB;

-- 테이블의 컬럼 출력
DESC EMP; -- 인텔리제이에서는 안됨

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP;

-- DUAL : 가상 테이블
SELECT SYSDATE FROM DUAL;
SELECT 4 * 7 FROM DUAL;
SELECT '4' * 7 FROM DUAL;
SELECT 'HELLO' || ' ' || 'ORACLE' FROM DUAL;
SELECT ROUND(10.5) FROM DUAL;

SELECT ENAME, SAL, SAL * 12 FROM EMP;

-- ALIAS (컬럼 정보)
SELECT ENAME AS 이름, SAL AS "월 급", SAL * 12 "연 봉" FROM EMP;

-- DISTINCT : 중복행 삭제 --> GROUP BY
SELECT DISTINCT DEPTNO FROM EMP;
SELECT DISTINCT JOB FROM EMP;
